# Generated by Django 3.1.2 on 2020-11-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20201111_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='location_ID',
        ),
        migrations.AddField(
            model_name='certificate',
            name='location_ID',
            field=models.CharField(default=112233, max_length=20),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='product_ID',
        ),
        migrations.AddField(
            model_name='certificate',
            name='product_ID',
            field=models.CharField(default=432421, max_length=20),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='teststand_ID',
        ),
        migrations.AddField(
            model_name='certificate',
            name='teststand_ID',
            field=models.CharField(default=333333, max_length=20),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='user_ID',
        ),
        migrations.AddField(
            model_name='certificate',
            name='user_ID',
            field=models.CharField(default=423413, max_length=20),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='service',
            name='teststand_ID',
        ),
        migrations.AddField(
            model_name='service',
            name='teststand_ID',
            field=models.CharField(default=328478234, max_length=20),
            preserve_default=False,
        ),
    ]
